language: java
jdk:
  - openjdk11

branches:
  only:
    - master

# Travis CI 서버의 Cache 활성화
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

# clean 후 Build (Build시 자동으로 test 수행)
script: "./gradlew clean build"

# slack notification
notifications:
  slack: $SLACK

deploy:
  provider: heroku
  api_key:
      secure: $HEROKU_API_KEY
  app:
    eussya-eussya-api
