language: java
jdk:
- openjdk11
branches:
  only:
  - master

# 실행전 접근 권한 설정
before_install:
  - chmod +x gradlew

# Travis CI 서버의 Cache 활성화
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.gradle"

# gradle build
script: "./gradlew clean build"

# slack notification
notifications:
  slack:
    secure: kzL5utNXHCbzex0uc3vjltUHb0TszMTCRwkY37CjTdplJ7fafjDqg4rraKOYJvHDoNg6UVdLjFB0eC55nMLzCu9rnPFPmVcWCkIRlbPmAb1G29uUeZd+GTxMNdikFET4s32nL5RvCPMeS4o73sJFsv/R9CgJxd55GSlsyIx8v0ZF/s5Q1j+2BAuPKjPuWgt+zZXxXPDtZ4zZkJrMvShoipKjupt9UOayHOqod36woy27Lfj/bHpomu1nmkDxp1yEfMRush0OsPWBnwTnw+eIu9ALyH5gzU/MuRH2QcDNUVmlnbEM74tIZYPZyqWvBr3Zd64Ju0ySfPDd/8v5YBZmeX6Z4yEmOssYynkjdx0+ynj1Qrs/GO+k9cds/WWiZl4VNi30ZsWR0yB1Rq2EYIq+E5J8iwKDeJdQP7DyByPKDyxSqgrBx9bjFoCFSvFciwFGrYW5YYI/GolJxt8POT/wpFrf8j0Rw1TxgDMaJm1xrZ+T/9QxY2QC32Rh3xYKO39qIJ2njKNGTSCpja61QgATdBAEwIGseMfdmnlAu41Cd9bYSmJTA4xISVA22XDSn0Htc7EKMVY6lbnMGf001C8KfFoGcTsr7/pmUNoTRsUjEuwgUuLGLOFyIw3NETEM98umnjpfdjR25P++UpFn3NbZQdfbC1qIzEkMJuviFTsoOMA=
before_deploy:
  - zip -r eussya-eussya-api *
  - mkdir -p deploy
  - mv eussya-eussya-api.zip deploy/eussya-eussya-api.zip

after_success:
  - ./gradlew jacocoTestReport coveralls -Djdk.tls.client.protocols="TLSv1,TLSv1.1,TLSv1.2"

# aws code deploy
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: eussya-eussya-api #  S3 버킷
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    wait_until_deployed: true
    on:
      repo: sproutt/eussya-eussya-api #Github 주소
      branch: master

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: eussya-eussya-api # S3 버킷
    key: eussya-eussya-api.zip # S3 버킷에 저장된 springboot-webservice.zip 파일을 EC2로 배포
    bundle_type: zip
    application: eussya-eussya-api # 웹 콘솔에서 등록한 CodeDeploy 어플리케이션
    deployment_group: sproutt # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait_until_deployed: true
    on:
      repo: sproutt/eussya-eussya-api #Github 주소
      branch: master
