# DB
spring:
  h2:
    console:
      enabled: true
      path: /h2-console


  #gmail SMTP
  mail:
    host: smtp.gmail.com
    port: 587
    default-encoding: UTF-8
    protocol: smtp
    username: [gmail계정@gmail.com]
    password: [gmail비밀번호]
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

token:
  key: Authorization