# DB
spring:
  h2:
    console:
      enabled: true
      path: /h2-console


  #gmail SMTP
  mail:
    host: smtp.gmail.com
    port: 587
    default-encoding: UTF-8
    protocol: smtp
    username: ENC(9NlYFfJbK5Epx/lOVqJGRvbtU5BWSytOZx8qNOgf1tE=)
    password: ENC(QM4Aq26vJvLXQcvIBRlP5UUOkE33ZB0P)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  header: Authorization
  secret: secret

social:
  github:
    url: https://api.github.com/user
  google:
    url: https://www.googleapis.com/oauth2/v2/userinfo
  facebook:
    url: https://graph.facebook.com/v6.0/me

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${JASYPT_PASSWORD}

api:
  cors:
    allow-origins:
      -ENC(7Al74gfGXcAvd/D4S93NeuVCbIR8UHqwaGnaWbvkzc8=)
      -ENC(jCH7aQtVVnhYmIhR4YQgnQbLMjjSZt7EGObYZbE4clY=)
      -ENC(D/AcDrURLhFwSjkXlm+jZjGKBIfhvi37PCMnIu2F6JDMFQx1MT6dGg==)