# DB
spring:
  h2:
    console:
      enabled: true
      path: /h2-console


  #gmail SMTP
  mail:
    host: smtp.gmail.com
    port: 587
    default-encoding: UTF-8
    protocol: smtp
    username: $MAIL_EMAIL
    password: $MAIL_PASSWORD
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

token:
  key: Authorization