# DB
spring:
  h2:
    console:
      enabled: true
      path: /h2-console


  #gmail SMTP
  mail:
    host: smtp.gmail.com
    port: 587
    default-encoding: UTF-8
    protocol: smtp
    username: ${MAIL_EMAIL}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

token:
  key: Authorization

social:
  github:
    client_id: 129232facea28c8d152b
    url: https://api.github.com/user
  google:
    client_id: 270372707971-82pnb1eqkm76q9lafh2f7q7f17tehrdh.apps.googleusercontent.com
    url: https://www.googleapis.com/oauth2/v2/userinfo